theme: jekyll-theme-cayman
title: AI For Mankind
description: Mobilizing the tech community to work on world challenging problems using AI and Data. 
Creating solutions that bring positive impacts to the world. Together we can make things happen.
