theme: jekyll-theme-cayman
title: AI For Mankind
description: Mobilizing the tech community to work on world challenging problems using AI and Data. <br /> Building a grassroot community of volunteers to create solutions using AI and Data to bring positive impacts to society at large.
